name: Android CI - Personal Build

on:
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab in GitHub
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK with Gradle
      # We use 'assembleDebug' instead of 'assembleRelease'
      # because debug builds don't require explicit signing keys.
      run: ./gradlew assembleDebug

    - name: Find Debug APK path
      # The exact filename might vary slightly (e.g., app-debug.apk)
      # This step helps find the correct path dynamically.
      id: find_apk
      run: |
        APK_PATH=$(find ${{ github.workspace }}/app/build/outputs/apk/debug -name "*.apk" | head -n 1)
        echo "APK_PATH=$APK_PATH" >> $GITHUB_OUTPUT

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: ${{ steps.find_apk.outputs.APK_PATH }}
        # Retention set to 1 day to save storage space
        retention-days: 1
