name: Android CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Retrieve version name
      run: echo VERSION_NAME=$(date "+%Y%m%d")_$(echo ${{ github.event.head_commit.id }} | head -c 7) >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Sign APK (temporary debug key + zipalign)
      run: |
        echo "Generating temporary debug keystore..."
        keytool -genkeypair -v \
          -keystore debug.keystore \
          -alias androiddebugkey \
          -storepass android \
          -keypass android \
          -keyalg RSA \
          -validity 10000 \
          -dname "CN=CI, OU=CI, O=CI, L=CI, ST=CI, C=CI"

        APK_UNSIGNED="${{ github.workspace }}/app/build/outputs/apk/release/app-release-unsigned.apk"
        APK_SIGNED="${{ github.workspace }}/app/build/outputs/apk/release/app-release-unsigned-signed.apk"
        APK_ALIGNED="${{ github.workspace }}/app/build/outputs/apk/release/fcmfix-ci-${{ env.VERSION_NAME }}.apk"

        echo "Signing APK..."
        jarsigner -verbose \
          -keystore debug.keystore \
          -storepass android \
          -keypass android \
          "$APK_UNSIGNED" androiddebugkey \
          -signedjar "$APK_SIGNED"

        echo "Aligning APK..."
        zipalign -v -p 4 "$APK_SIGNED" "$APK_ALIGNED"
    
    - name: Upload built apk
      uses: actions/upload-artifact@v4
      with:
        name: fcmfix-ci
        path: ${{ github.workspace }}/app/build/outputs/apk/release/fcmfix-ci-${{ env.VERSION_NAME }}.apk
